In [61]:
import pandas as pd
import numpy as np


In [67]:
df= pd.read_csv('50_Startups.csv')

In [68]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42  California  166187.94

In [69]:
# extrating x dataset from the dataframe
x=df.iloc[0:,0:4].values
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'California'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'New York'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'California'],
       [100671.96, 91790.61, 249744.55, 'Florida'],
       [93863.75, 127320.38, 249839.44, 'California'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79

In [70]:
# exracting y dataset
y= df.iloc[0:,4:].values

In [ ]:
#  since x contain categorical data so we will convert this categorical data into numerical data
# following methods are employed to do this task
# 1.Label Encoding
# 2.One-Hot Encoding

# 1.Label -Encoding: involves assigning a unique integer to each
#  category in a categorical feature. For example, if you have a 
# feature "Color" with categories "Red," "Blue," and "Green,"
#  label encoding would transform these categories into 
# numerical values such as:
# "Red" -> 0
# "Blue" -> 1
# "Green" -> 2

# 2.One-Hot Encoding : One-hot encoding addresses the issue of
#  implied ordinality by creating a new binary column (0 or 1) 
# for each category. Each row in the dataset will have a 1 in the 
# column corresponding to its category and 0s in all other 
# columns. For the same "Color" feature, one-hot encoding
#  would create three new columns:

# Color_Red: [1, 0, 0] (for Red)
# Color_Blue: [0, 1, 0] (for Blue)
# Color_Green: [0, 0, 1] (for Green)

In [ ]:
# Label.fit_transform(x[:, 3:]).shape
# x[:,2:].shape[1]

In [71]:
from sklearn.preprocessing import LabelEncoder
Label = LabelEncoder()
x[:, 3:]= Label.fit_transform(x[:, 3:].ravel()).reshape(50,1)
x


array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 0],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 2],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 0],
       [100671.96, 91790.61, 249744.55, 1],
       [93863.75, 127320.38, 249839.44, 0],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 2],
       [86419.7, 153514.11, 0.0, 1],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 30331

In [72]:
x

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 0],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 2],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 0],
       [100671.96, 91790.61, 249744.55, 1],
       [93863.75, 127320.38, 249839.44, 0],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 2],
       [86419.7, 153514.11, 0.0, 1],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 30331

In [73]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer([('encoder',OneHotEncoder(),[3])],remainder='passthrough')
ct.fit_transform(x)
# np.array(ct.fit_transform(x))
x= np.array(ct.fit_transform(x))
x.shape

(50, 6)

In [77]:
from sklearn.model_selection import  train_test_split
x_train,x_test,y_train,_y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [79]:
print ('X Shape-',x.shape)
print ('Y Shape-', y.shape)
print ('X_train Shape-',x_train.shape)
print ('Y_train Shape-',y_train.shape)
print ('X_test Shape-',x_test.shape)
print ('Y_test Shape-',y_test.shape)


X Shape- (50, 6)
Y Shape- (50, 1)
X_train Shape- (40, 6)
Y_train Shape- (40, 1)
X_test Shape- (10, 6)


NameError: name 'y_test' is not defined